--!strict

local AnalyticsService = require(script.Parent.Services.AnalyticsService)
local DataService = require(script.Parent.Services.DataService)
local MachineService = require(script.Parent.Services.MachineService)
local PlotService = require(script.Parent.Services.PlotService)
local ProductionService = require(script.Parent.Services.ProductionService)
local RemoteService = require(script.Parent.Services.RemoteService)
local RobotService = require(script.Parent.Services.RobotService)
local RobotVisualService = require(script.Parent.Services.RobotVisualService)
local SalvageService = require(script.Parent.Services.SalvageService)
local StateService = require(script.Parent.Services.StateService)
local UpgradeService = require(script.Parent.Services.UpgradeService)
local WorldService = require(script.Parent.Services.WorldService)
local ZoneService = require(script.Parent.Services.ZoneService)

local function start()
	WorldService.Init()
	RemoteService.Init()
	PlotService.Init()
	StateService.Init()
	SalvageService.Init()
	MachineService.Init()
	RobotService.Init()
	RobotVisualService.Init()
	UpgradeService.Init()
	ProductionService.Init()
	AnalyticsService.Init()
	ZoneService.Init()
	DataService.Init()
	print("[ScrapToBotFactory] Graybox gameplay services initialized")
end

start()
