--!strict

export type Rarity = "Common" | "Uncommon" | "Rare" | "Epic"

export type RobotDefinition = {
	Id: string,
	DisplayName: string,
	Family: string,
	Rarity: Rarity,
	Weight: number,
	ProductionPerSecond: number,
	RecycleCredits: number,
	Visual: {
		Body: string,
		Head: string,
		Tool: string,
		Locomotion: string,
		Accent: string,
	},
}

local Robots: { [string]: RobotDefinition } = {
	TinScout = {
		Id = "TinScout",
		DisplayName = "Tin Scout",
		Family = "Salvager",
		Rarity = "Common",
		Weight = 180,
		ProductionPerSecond = 1,
		RecycleCredits = 20,
		Visual = {
			Body = "Compact",
			Head = "Round",
			Tool = "Grabber",
			Locomotion = "Wheels",
			Accent = "Steel",
		},
	},
	BoltBuddy = {
		Id = "BoltBuddy",
		DisplayName = "Bolt Buddy",
		Family = "Salvager",
		Rarity = "Common",
		Weight = 160,
		ProductionPerSecond = 1.1,
		RecycleCredits = 22,
		Visual = {
			Body = "Compact",
			Head = "Box",
			Tool = "Magnet",
			Locomotion = "Wheels",
			Accent = "Orange",
		},
	},
	WireWisp = {
		Id = "WireWisp",
		DisplayName = "Wire Wisp",
		Family = "Technician",
		Rarity = "Common",
		Weight = 145,
		ProductionPerSecond = 1.2,
		RecycleCredits = 24,
		Visual = {
			Body = "Orb",
			Head = "Lens",
			Tool = "Coil",
			Locomotion = "Hover",
			Accent = "Blue",
		},
	},
	RivetRunner = {
		Id = "RivetRunner",
		DisplayName = "Rivet Runner",
		Family = "Hauler",
		Rarity = "Common",
		Weight = 125,
		ProductionPerSecond = 1.3,
		RecycleCredits = 26,
		Visual = {
			Body = "Utility",
			Head = "Round",
			Tool = "Clamp",
			Locomotion = "Legs",
			Accent = "Yellow",
		},
	},
	CopperClaw = {
		Id = "CopperClaw",
		DisplayName = "Copper Claw",
		Family = "Salvager",
		Rarity = "Uncommon",
		Weight = 82,
		ProductionPerSecond = 1.8,
		RecycleCredits = 45,
		Visual = {
			Body = "Utility",
			Head = "Box",
			Tool = "Claw",
			Locomotion = "Wheels",
			Accent = "Copper",
		},
	},
	CircuitMender = {
		Id = "CircuitMender",
		DisplayName = "Circuit Mender",
		Family = "Technician",
		Rarity = "Uncommon",
		Weight = 70,
		ProductionPerSecond = 2,
		RecycleCredits = 50,
		Visual = {
			Body = "Compact",
			Head = "Lens",
			Tool = "Welder",
			Locomotion = "Legs",
			Accent = "Green",
		},
	},
	GearGlider = {
		Id = "GearGlider",
		DisplayName = "Gear Glider",
		Family = "Courier",
		Rarity = "Uncommon",
		Weight = 62,
		ProductionPerSecond = 2.2,
		RecycleCredits = 55,
		Visual = {
			Body = "Orb",
			Head = "Round",
			Tool = "Cargo",
			Locomotion = "Hover",
			Accent = "Teal",
		},
	},
	ForgeHound = {
		Id = "ForgeHound",
		DisplayName = "Forge Hound",
		Family = "Hauler",
		Rarity = "Uncommon",
		Weight = 55,
		ProductionPerSecond = 2.4,
		RecycleCredits = 60,
		Visual = {
			Body = "Heavy",
			Head = "Visor",
			Tool = "Pusher",
			Locomotion = "Legs",
			Accent = "Red",
		},
	},
	CoreDriller = {
		Id = "CoreDriller",
		DisplayName = "Core Driller",
		Family = "Extractor",
		Rarity = "Rare",
		Weight = 38,
		ProductionPerSecond = 3.5,
		RecycleCredits = 110,
		Visual = {
			Body = "Heavy",
			Head = "Lens",
			Tool = "Drill",
			Locomotion = "Tracks",
			Accent = "Violet",
		},
	},
	ArcWelder = {
		Id = "ArcWelder",
		DisplayName = "Arc Welder",
		Family = "Technician",
		Rarity = "Rare",
		Weight = 30,
		ProductionPerSecond = 3.9,
		RecycleCredits = 125,
		Visual = {
			Body = "Utility",
			Head = "Visor",
			Tool = "ArcTool",
			Locomotion = "Hover",
			Accent = "Cyan",
		},
	},
	Magnetitan = {
		Id = "Magnetitan",
		DisplayName = "Magnetitan",
		Family = "Salvager",
		Rarity = "Rare",
		Weight = 24,
		ProductionPerSecond = 4.4,
		RecycleCredits = 145,
		Visual = {
			Body = "Heavy",
			Head = "Box",
			Tool = "TwinMagnet",
			Locomotion = "Tracks",
			Accent = "Magenta",
		},
	},
	NovaForeman = {
		Id = "NovaForeman",
		DisplayName = "Nova Foreman",
		Family = "Foreman",
		Rarity = "Epic",
		Weight = 9,
		ProductionPerSecond = 7.5,
		RecycleCredits = 300,
		Visual = {
			Body = "Command",
			Head = "Visor",
			Tool = "MultiTool",
			Locomotion = "Hover",
			Accent = "Gold",
		},
	},
}

local FirstRevealPool = table.freeze({ "TinScout", "BoltBuddy", "WireWisp", "CopperClaw" })

return table.freeze({
	Definitions = table.freeze(Robots),
	FirstRevealPool = FirstRevealPool,
})
